### ISSUE TITLE
did not receive a valid HTTP response !

### ISSUE THREAD

**Issue by gypais** [WiwiWillou/tydom2mqtt#21]
Hi, I installed the official Mosquitto broker 5.1 addon. with login / password because for the conf of tydom2mqtt the conf imposes one.
the broker works, because under the shell I manage to publish a message and see it under mqtt explorer
I installed tydom2mqtt release_0.96c, but once configured I got an error message ...

`STARTING TYDOM2MQTT
Dectecting environnement......
/data/options.json detected ! Hassio Addons Environnement : parsing options.json....
{'TYDOM_MAC': '001A250XXX', 'TYDOM_IP': '192.168.0.10', 'TYDOM_PASSWORD': 'XXX!', 'TYDOM_ALARM_PIN': 123456, 'TYDOM_ALARM_HOME_ZONE': 1, 'TYDOM_ALARM_NIGHT_ZONE': 2, 'MQTT_HOST': 'localhost', 'MQTT_USER': 'jppmqtt', 'MQTT_PASSWORD': 'jppmqtt', 'MQTT_PORT': 1883, 'MQTT_SSL': False, 'log_level': 'info'}
Initialising TydomClient Class
Setting local mode context.
Starting main loop_task
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Attempting MQTT connection...
MQTT host :  localhost
MQTT user :  jppmqtt
##################################
Subscribing to :  +/tydom/#
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
TYDOM WEBSOCKET CONNECTION INITIALISING....                     
Building headers, getting 1st handshake and authentication....
Upgrading http connection to websocket....
Attempting websocket connection with tydom hub.......................
Host Target :
192.168.0.10
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<listen_tydom_forever() done, defined at /opt/tydom2mqtt/main.py:104> exception=InvalidMessage('did not receive a valid HTTP response')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/websockets/client.py", line 101, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/usr/lib/python3.8/site-packages/websockets/http.py", line 160, in read_response
    headers = await read_headers(stream)
  File "/usr/lib/python3.8/site-packages/websockets/http.py", line 188, in read_headers
    raise ValueError(f"invalid HTTP header line: {d(line)}") from None
ValueError: invalid HTTP header line:   realm="Protected Area",
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/tydom2mqtt/main.py", line 113, in listen_tydom_forever
    await tydom_client.connect()
  File "/opt/tydom2mqtt/tydomConnector.py", line 120, in connect
    self.connection = await websockets.client.connect('wss://{}:443/mediation/client?mac={}&appli=1'.format(self.host, self.mac),
  File "/usr/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/usr/lib/python3.8/site-packages/websockets/client.py", line 290, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/usr/lib/python3.8/site-packages/websockets/client.py", line 103, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
Starting /opt/tydom2mqtt/main.py`

Other people have the same error as me
I am with Home Assistant OS 5.9 and tydom 1

Thanks for your help
happy end of year

**Comment by Zatow** [comment]
Hello,
I have the same problem, did you manage to solve it?
Thanks for you help.

**Comment by mrwiwi** [comment]
Can you guys ping the Tydom IP address manually ?

**Comment by Zatow** [comment]
yes TYDOM responds to the ping
