### ISSUE TITLE
Error start

### ISSUE THREAD

**Issue by Shadorlo** [WiwiWillou/tydom2mqtt#47]
```
2023-09-30 16:25:41,414 - Starting tydom2mqtt
2023-09-30 16:25:41,416 - Hassio environment detected: loading configuration from /data/options.json
2023-09-30 16:25:41,421 - Validating configuration ({
    "deltadore_login": null,
    "deltadore_password": "",
    "log_level": "ERROR",
    "mqtt_host": "localhost",
    "mqtt_password": "u*****r",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "userrrrr",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "mediation.tydom.com",
    "tydom_mac": "xxxxxxxx",
    "tydom_password": "C******1"
}
2023-09-30 16:25:41,423 - The configuration is valid
2023-09-30 16:25:42,323 - tydom.MessageHandler - ERROR   - Error on parsing tydom response ('NoneType' object has no attribute 'publish')
2023-09-30 16:25:42,325 - tydom.MessageHandler - ERROR   - Incoming data ([{"id":1645988476,"endpoints":[{"id":1645988476,"error":0,"data":[{"name":"authorization","validity":"upToDate","value":"STOP"},{"name":"setpoint","validity":"upToDate","value":null},{"name":"thermicLevel","validity":"upToDate","value":"STOP"},{"name":"hvacMode","validity":"upToDate","value":"NORMAL"},{"name":"timeDelay","validity":"upToDate","value":0},{"name":"temperature","validity":"upToDate","value":27.320},{"name":"tempoOn","validity":"upToDate","value":false},{"name":"antifrostOn","validity":"upToDate","value":false},{"name":"loadSheddingOn","validity":"upToDate","value":false},{"name":"openingDetected","validity":"upToDate","value":false},{"name":"presenceDetected","validity":"upToDate","value":false},{"name":"absence","validity":"upToDate","value":false},{"name":"productionDefect","validity":"upToDate","value":false},{"name":"batteryCmdDefect","validity":"upToDate","value":false},{"name":"tempSensorDefect","validity":"upToDate","value":false},{"name":"tempSensorShortCut","validity":"upToDate","value":false},{"name":"tempSensorOpenCirc","validity":"upToDate","value":false},{"name":"boostOn","validity":"upToDate","value":false},{"name":"anticipCoeff","validity":"upToDate","value":30}]}]},{"id":1652815136,"endpoints":[{"id":1652815136,"error":0,"data":[{"name":"thermicDefect","validity":"upToDate","value":false}]}]}]
)
2023-09-30 16:25:42,326 - tydom.MessageHandler - ERROR   - 'NoneType' object has no attribute 'publish'
Traceback (most recent call last):
  File "/app/tydom/MessageHandler.py", line 360, in parse_response
    await self.parse_devices_data(parsed=parsed)
  File "/app/tydom/MessageHandler.py", line 470, in parse_devices_data
    await self.parse_endpoint_data(endpoint, i["id"])
  File "/app/tydom/MessageHandler.py", line 707, in parse_endpoint_data
    await new_sh_hvac.update()
  File "/app/sensors/Boiler.py", line 114, in update
    await self.setup()
  File "/app/sensors/Boiler.py", line 109, in setup
    self.mqtt.mqtt_client.publish(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish'
```

Bonjour, je possède cette erreur lors du démarrage il se connècte bien mais s'éteint après après ce pavet d'erreur :
Discord : Shadorlo

merci bonne journée :;)
Je tourne en local via rj45 je n'ai ouvert aucun port du raspberry vers l'extérieur

**Comment by Shadorlo** [comment]
Hey,
J'ai réinstaller homeassistant,
J'ai toujours le même problème haha; 

`2023-10-01 20:06:07,303 - Starting tydom2mqtt
2023-10-01 20:06:07,305 - Hassio environment detected: loading configuration from /data/options.json
2023-10-01 20:06:07,312 - Validating configuration ({
    "deltadore_login": null,
    "deltadore_password": "",
    "log_level": "INFO",
    "mqtt_host": "localhost",
    "mqtt_password": "u************0",
    "mqtt_port": 1883,
    "mqtt_ssl": false,
    "mqtt_user": "user132456789",
    "thermostat_custom_presets": null,
    "tydom_alarm_home_zone": 1,
    "tydom_alarm_night_zone": 2,
    "tydom_alarm_pin": "",
    "tydom_ip": "mediation.tydom.com",
    "tydom_mac": "001A25020082",
    "tydom_password": "C******1"
}
2023-10-01 20:06:07,314 - The configuration is valid
2023-10-01 20:06:07,316 - tydom.TydomClient    - INFO    - Configure remote mode (mediation.tydom.com)
2023-10-01 20:06:07,360 - mqtt.MqttClient      - INFO    - Connecting to mqtt broker (host=localhost, port=1883, user=user132456789, ssl=False)
2023-10-01 20:06:07,417 - tydom.TydomClient    - INFO    - Connecting to tydom
2023-10-01 20:06:07,859 - mqtt.MqttClient      - WARNING - MQTT connection error : Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 1883), [Errno 99] Address not available
2023-10-01 20:06:08,017 - tydom.TydomClient    - INFO    - Connected to tydom
2023-10-01 20:06:08,018 - tydom.TydomClient    - INFO    - Setup tydom client
2023-10-01 20:06:08,326 - tydom.MessageHandler - INFO    - Device update (id=1645988476, endpoint=1645988476, name=Chauffage 1, type=boiler)
2023-10-01 20:06:08,328 - tydom.MessageHandler - ERROR   - Error on parsing tydom response ('NoneType' object has no attribute 'publish')
2023-10-01 20:06:08,330 - tydom.MessageHandler - ERROR   - Incoming data ([{"id":1645988476,"endpoints":[{"id":1645988476,"error":0,"data":[{"name":"authorization","validity":"upToDate","value":"STOP"},{"name":"setpoint","validity":"upToDate","value":null},{"name":"thermicLevel","validity":"upToDate","value":"STOP"},{"name":"hvacMode","validity":"upToDate","value":"NORMAL"},{"name":"timeDelay","validity":"upToDate","value":0},{"name":"temperature","validity":"upToDate","value":28.670},{"name":"tempoOn","validity":"upToDate","value":false},{"name":"antifrostOn","validity":"upToDate","value":false},{"name":"loadSheddingOn","validity":"upToDate","value":false},{"name":"openingDetected","validity":"upToDate","value":false},{"name":"presenceDetected","validity":"upToDate","value":false},{"name":"absence","validity":"upToDate","value":false},{"name":"productionDefect","validity":"upToDate","value":false},{"name":"batteryCmdDefect","validity":"upToDate","value":false},{"name":"tempSensorDefect","validity":"upToDate","value":false},{"name":"tempSensorShortCut","validity":"upToDate","value":false},{"name":"tempSensorOpenCirc","validity":"upToDate","value":false},{"name":"boostOn","validity":"upToDate","value":false},{"name":"anticipCoeff","validity":"upToDate","value":30}]}]},{"id":1652815136,"endpoints":[{"id":1652815136,"error":15,"data":[{"name":"thermicDefect","validity":"expired","value":false}]}]}]
)
2023-10-01 20:06:08,331 - tydom.MessageHandler - ERROR   - 'NoneType' object has no attribute 'publish'
Traceback (most recent call last):
  File "/app/tydom/MessageHandler.py", line 360, in parse_response
    await self.parse_devices_data(parsed=parsed)
  File "/app/tydom/MessageHandler.py", line 470, in parse_devices_data
    await self.parse_endpoint_data(endpoint, i["id"])
  File "/app/tydom/MessageHandler.py", line 707, in parse_endpoint_data
    await new_sh_hvac.update()
  File "/app/sensors/Boiler.py", line 114, in update
    await self.setup()
  File "/app/sensors/Boiler.py", line 109, in setup
    self.mqtt.mqtt_client.publish(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish'
2023-10-01 20:06:08,361 - tydom.MessageHandler - WARNING - Unknown message type received ([]
)
2023-10-01 20:06:12,068 - tydom.MessageHandler - INFO    - Device update (id=1645988476, endpoint=1645988476, name=Chauffage 1, type=boiler)
2023-10-01 20:06:12,069 - tydom.MessageHandler - ERROR   - Error on parsing tydom response ('NoneType' object has no attribute 'publish')
2023-10-01 20:06:12,070 - tydom.MessageHandler - ERROR   - Incoming data ([{"id": 1645988476, "endpoints": [{"id": 1645988476, "error": 0, "data": [{"name": "temperature", "validity": "upToDate", "value": 28.58}]}]}])
2023-10-01 20:06:12,071 - tydom.MessageHandler - ERROR   - 'NoneType' object has no attribute 'publish'
Traceback (most recent call last):
  File "/app/tydom/MessageHandler.py", line 360, in parse_response
    await self.parse_devices_data(parsed=parsed)
  File "/app/tydom/MessageHandler.py", line 470, in parse_devices_data
    await self.parse_endpoint_data(endpoint, i["id"])
  File "/app/tydom/MessageHandler.py", line 707, in parse_endpoint_data
    await new_sh_hvac.update()
  File "/app/sensors/Boiler.py", line 114, in update
    await self.setup()
  File "/app/sensors/Boiler.py", line 109, in setup
    self.mqtt.mqtt_client.publish(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish'`

**Comment by mrwiwi** [comment]
Salut, ce tydom2mqtt est déprécié, lis bien les premières lignes il a été repris par des gens bien plus compétents que moi ;)

**Comment by Shadorlo** [comment]
Salut, merci de l'information aurais tu le lien d'un autre Tydom compatible homeassistant ?
merci !
